FROM ubuntu:2204

RUN apt update && apt install -y python python-pip libboost-all-dev pybind11-dev && apt clean all
RUN git clone https://github.com/vm6502q/FindAFactor && cd FindAFactor && pip install .

COPY findafactor.py /
COPY run-findafactor.sh

ENTRYPOINT /root/run-findafactor.sh 
