FROM ubuntu:22.04

RUN apt update && apt install -y python3 python-pip libboost-all-dev pybind11-dev && apt clean all
RUN git clone https://github.com/vm6502q/FindAFactor && cd FindAFactor && pip install .

COPY findafactor.py /
COPY run-findafactor.sh /root

ENTRYPOINT /root/run-findafactor.sh 
