FROM ubuntu:24.04

RUN apt update && apt install -y python3 python3-pip python-is-python3 git build-essential cmake libboost-all-dev pybind11-dev mathomatic-primes bc openssl gawk && apt clean all
RUN git clone https://github.com/vm6502q/FindAFactor && cd FindAFactor && pip install --break-system-packages . && pip install --break-system-packages scikit-optimize && pip cache purge

COPY /runfiles/run-* /root/
RUN chmod 755 /root/run-*

ENTRYPOINT /root/run-findafactor.sh 
